version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - [%(filename)s:%(lineno)d]'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ../logs/app.log
    mode: 'a'
    maxBytes: 1048576  # 1MB (1,048,576 bytes)
    backupCount: 3  # Keep up to 3 old log files
    encoding: utf8

loggers:
  root:
    level: DEBUG
    handlers: [console, rotating_file]

root:
  level: DEBUG
  handlers: [console, rotating_file]
